### ISSUE TITLE
Feature request for outgoing ip/interface

### ISSUE THREAD

**Issue by khizarsonu** [brozeph/simple-socks#38]
lets take an example

curl ifconfig.io --interface "my.interface.ip.address"

if is possible to add interface ip or outgoing interface ip?

**Comment by brozeph** [comment]
@khizarsonu. someone had made a PR a while back that used FFA to do this: <https://github.com/highload-zone/simple-socks/tree/patch-1> 

Basically, in the `options` passed during construction, the `interface` could be specified and then get and set socketopt is used by FFI underneath the covers to bind to the specified interface. This was well written and tested - you could try this fork.

Ultimately, I chose not to merge because it wasn't clear it would work on Windows, I didn't dig the FFI dependency (I was trying to keep the library really lightweight) and, I don't actually think this is  needed in more recent Node.js releases based on the behavior of the underlying `net.listen` (<https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_options_callback>) which is used to create the SOCKS server.

So... effectively, to bind to a specific interface, the following should work too:

```javascript
const
	serverOptions = {
		host : '192.168.0.112', // <-- interface IP goes here
		port : 1080
	},
	socks5 = require('../dist/socks5'),
	server = socks5.createServer();

// start listening!
server.listen(options);
```

**Comment by brozeph** [comment]
Closing due to answer

**Comment by Ozguner** [comment]
> @khizarsonu. someone had made a PR a while back that used FFA to do this: https://github.com/highload-zone/simple-socks/tree/patch-1
> 
> Basically, in the `options` passed during construction, the `interface` could be specified and then get and set socketopt is used by FFI underneath the covers to bind to the specified interface. This was well written and tested - you could try this fork.
> 
> Ultimately, I chose not to merge because it wasn't clear it would work on Windows, I didn't dig the FFI dependency (I was trying to keep the library really lightweight) and, I don't actually think this is needed in more recent Node.js releases based on the behavior of the underlying `net.listen` (https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_options_callback) which is used to create the SOCKS server.
> 
> So... effectively, to bind to a specific interface, the following should work too:
> 
> ```js
> const
> 	serverOptions = {
> 		host : '192.168.0.112', // <-- interface IP goes here
> 		port : 1080
> 	},
> 	socks5 = require('../dist/socks5'),
> 	server = socks5.createServer();
> 
> // start listening!
> server.listen(options);
> ```

unfortunately this did not work for me
