### ISSUE TITLE
How to view the raw client requests?

### ISSUE THREAD

**Issue by gerald-dotcom** [brozeph/simple-socks#39]
I'm trying to intercept Get, Post requests made by the client and modify by them accordingly under my preference.

I try so hard to read your code but fail miserably.

I've put console.log in the Connect function to log the raw buffer but it seems that raw buffer only contain the Dest. domain name not the Body (Whatever it's).

I'm already started to burn down. Appreciate your help! 

I could donate too.

**Comment by brozeph** [comment]
@gerald-dotcom, thank you for using `simple-socks`! To confirm, is your goal to modify the content as it comes back to the caller (scenario A below) or to modify the call before it is sent to the destination (scenario B below)?

Scenario A
```
[client] ->  [proxy server]  -> [destination]
[client] <- [modify content] <- [proxy server] <- [destination]
```

Scenario B
```
[client] -> [proxy server] -> [modify content] -> [destination]
[client] <- [proxy server] <- [destination]
```
.. or are you trying to do both?

**Comment by gerald-dotcom** [comment]
@brozeph Yeah both

**Comment by brozeph** [comment]
@gerald-dotcom - I think you might have better luck with a web proxy if your goal is to work specifically with the HTTP (GET, POST, etc.) protocol. This SOCKS proxy server can handle any type of TCP comms, but you'll need to do more work to parse and process the content to understand the HTTP verb, etc.

At this function in the code is where the data from the client is piped to the destination and the response from the destination is piped back to the client:
<https://github.com/brozeph/simple-socks/blob/master/src/socks5.js#L248>

Effectively, this is where you'd need to intercept and modify the traffic... for awareness, this would only work for an unencrypted (i.e. non-SSL / TLS) web request - otherwise, you won't be able to actually parse the content.
